// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsaCkeTnQkFuUeZpgPBIRdbR_hV80VRdE',
    appId: '1:190954318202:web:bba175151fa937512ccec3',
    messagingSenderId: '190954318202',
    projectId: 'air-sense-cb4e2',
    authDomain: 'air-sense-cb4e2.firebaseapp.com',
    storageBucket: 'air-sense-cb4e2.firebasestorage.app',
    measurementId: 'G-CPSVZBDFFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSqxULEOLds133lf_KPeFqGwBuGx52tKY',
    appId: '1:190954318202:android:7b47079524f14e9f2ccec3',
    messagingSenderId: '190954318202',
    projectId: 'air-sense-cb4e2',
    storageBucket: 'air-sense-cb4e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLQZ-HmnVKXoGFPNwz6KocEMwimdTQweU',
    appId: '1:190954318202:ios:48f61c2ad9ef2dc42ccec3',
    messagingSenderId: '190954318202',
    projectId: 'air-sense-cb4e2',
    storageBucket: 'air-sense-cb4e2.firebasestorage.app',
    iosBundleId: 'com.example.airSense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLQZ-HmnVKXoGFPNwz6KocEMwimdTQweU',
    appId: '1:190954318202:ios:e41d53fca3c910e42ccec3',
    messagingSenderId: '190954318202',
    projectId: 'air-sense-cb4e2',
    storageBucket: 'air-sense-cb4e2.firebasestorage.app',
    iosBundleId: 'com.example.airSenseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsaCkeTnQkFuUeZpgPBIRdbR_hV80VRdE',
    appId: '1:190954318202:web:7a507931cbd17f6e2ccec3',
    messagingSenderId: '190954318202',
    projectId: 'air-sense-cb4e2',
    authDomain: 'air-sense-cb4e2.firebaseapp.com',
    storageBucket: 'air-sense-cb4e2.firebasestorage.app',
    measurementId: 'G-S4EB0PD7ZH',
  );
}
